/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class file_engine_dllInterface_GetStartMenu */

#ifndef _Included_file_engine_dllInterface_GetStartMenu
#define _Included_file_engine_dllInterface_GetStartMenu
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     file_engine_dllInterface_GetStartMenu
 * Method:    getStartMenu
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_file_engine_dllInterface_GetStartMenu_getStartMenu
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
