/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class file_engine_dllInterface_EmptyRecycleBin */

#ifndef _Included_file_engine_dllInterface_EmptyRecycleBin
#define _Included_file_engine_dllInterface_EmptyRecycleBin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     file_engine_dllInterface_EmptyRecycleBin
 * Method:    emptyRecycleBin
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_file_engine_dllInterface_EmptyRecycleBin_emptyRecycleBin
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
