/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class file_engine_dllInterface_GetAscII */

#ifndef _Included_file_engine_dllInterface_GetAscII
#define _Included_file_engine_dllInterface_GetAscII
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     file_engine_dllInterface_GetAscII
 * Method:    getAscII
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_file_engine_dllInterface_GetAscII_getAscII
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
