/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class file_engine_dllInterface_SystemThemeInfo */

#ifndef _Included_file_engine_dllInterface_SystemThemeInfo
#define _Included_file_engine_dllInterface_SystemThemeInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     file_engine_dllInterface_SystemThemeInfo
 * Method:    isDarkThemeEnabled
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_file_engine_dllInterface_SystemThemeInfo_isDarkThemeEnabled
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
